services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - URL=http://localhost:3030
    - PORT=3030
    - DATABASE_URL=postgresql://postgres@127.0.0.1:5432/auto_mart
language: node_js
node_js:
  - node
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test
before_script:
  - psql -c 'create database auto_mart;' -U postgres
after_success:
  - npm run coverage